### ISSUE TITLE
Requirements?

### ISSUE THREAD

**Issue by hrj** [lars-t-hansen/js-lock-and-condition#6]
Does this project require `Atomics` or will provide fallbacks (for example, using synchronous file apis / localdb apis / busy spins, etc)?

Would be nice if you added a note in the README. Thanks!

**Comment by lars-t-hansen** [comment]
> Does this project require `Atomics` 

Yes.

> or will provide fallbacks (for example, using synchronous file apis / localdb apis / busy spins, etc)?

No.  I don't think these are meaningful, once you're using shared memory.  Although, I do think of using shared memory for transport and `postMessage` for synchronization is an interesting variant.
